services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - db

  test:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    command: ["pytest", "--tb=short"]

volumes:
  postgres_data:
